cc_binary(
  name = "function_objects",
  srcs = ["function_objects.cc", "container_printer.h"],
)

cc_binary(
  name = "list",
  srcs = ["list.cc", "container_printer.h"],
)

cc_binary(
  name = "deque",
  srcs = ["deque.cc"],
)

cc_binary(
  name = "vector",
  srcs = ["vector.cc"],
)
