cc_binary(
  name = "strrchr",
  srcs = ["strrchr.cc", "container_printer.h"],
)

cc_binary(
  name = "string",
  srcs = ["string.cc", "container_printer.h"],
)

cc_binary(
  name = "heap",
  srcs = ["heap.cc", "container_printer.h"],
)

cc_binary(
  name = "stack",
  srcs = ["stack.cc"],
)

cc_binary(
  name = "array",
  srcs = ["array.cc"],
)

cc_binary(
  name = "unordered_multimap",
  srcs = ["unordered_multimap.cc"],
)

cc_binary(
  name = "multiset",
  srcs = ["multiset.cc"],
)

cc_binary(
  name = "unordered_map",
  srcs = ["unordered_map.cc", "container_printer.h"],
)

cc_binary(
  name = "map",
  srcs = ["map.cc", "container_printer.h"],
)

cc_binary(
  name = "unordered_set",
  srcs = ["unordered_set.cc", "container_printer.h"],
)

cc_binary(
  name = "set",
  srcs = ["set.cc", "container_printer.h"],
)

cc_binary(
  name = "function_objects",
  srcs = ["function_objects.cc", "container_printer.h"],
)

cc_binary(
  name = "forward_list",
  srcs = ["forward_list.cc"],
)

cc_binary(
  name = "list",
  srcs = ["list.cc", "container_printer.h"],
)

cc_binary(
  name = "deque",
  srcs = ["deque.cc"],
)

cc_binary(
  name = "vector",
  srcs = ["vector.cc"],
)
